# Generated by Django 5.0.4 on 2024-04-08 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=20, verbose_name='Menu')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False, verbose_name='Order Number')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Order Date')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='Total Price')),
                ('total_items', models.PositiveIntegerField(default=0, verbose_name='Total Items')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.menu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
