# Generated by Django 5.0.4 on 2024-04-08 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_alter_menu_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
    ]
